# Generated by Django 4.0.3 on 2022-04-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showvotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
